[package]
name = "hello-heroku"
version = "0.1.0"
authors = ["Tatsuya Kawano <tatsuya@hibaridb.org>"]

[dependencies]
nickel = "0.8.1"
regex = "0.1.71"
lazy_static = "0.2.1"

clippy = { version = "0.0.71", optional = true }
